/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grantmanagementsystem;

/**
 *
 * @author gregm
 */
public class RecourceHubGUI extends javax.swing.JFrame {

    /**
     * Creates new form RecourceHubGUI
     */
    public RecourceHubGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePagePanel = new javax.swing.JPanel();
        ReportGeneratorLogoLabel = new javax.swing.JLabel();
        RecourceHubLogoLabel = new javax.swing.JLabel();
        ReportGeneratorLabel = new javax.swing.JLabel();
        RecourceHubLabel = new javax.swing.JLabel();
        ReportGeneratorExplanationLabel = new javax.swing.JLabel();
        RecourceHubExplanationLabel1 = new javax.swing.JLabel();
        ReportGeneratorExplanationLabel1 = new javax.swing.JLabel();
        RecourceHubExplanationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HomePagePanel.setBackground(new java.awt.Color(51, 204, 255));

        ReportGeneratorLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analytics.png"))); // NOI18N

        RecourceHubLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourceHubLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/concept.png"))); // NOI18N

        ReportGeneratorLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        ReportGeneratorLabel.setForeground(new java.awt.Color(255, 255, 255));
        ReportGeneratorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorLabel.setText("Report Generator:");

        RecourceHubLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        RecourceHubLabel.setForeground(new java.awt.Color(255, 255, 255));
        RecourceHubLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourceHubLabel.setText("Recource hub:");

        ReportGeneratorExplanationLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 14)); // NOI18N
        ReportGeneratorExplanationLabel.setForeground(new java.awt.Color(255, 255, 255));
        ReportGeneratorExplanationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorExplanationLabel.setText("A report generator tool to provide insightful reports based ");

        RecourceHubExplanationLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 14)); // NOI18N
        RecourceHubExplanationLabel1.setForeground(new java.awt.Color(255, 255, 255));
        RecourceHubExplanationLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourceHubExplanationLabel1.setText("upload, organize and access educational recources");

        ReportGeneratorExplanationLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 14)); // NOI18N
        ReportGeneratorExplanationLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ReportGeneratorExplanationLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorExplanationLabel1.setText("on users activity, user growth, and recource usage");

        RecourceHubExplanationLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 14)); // NOI18N
        RecourceHubExplanationLabel.setForeground(new java.awt.Color(255, 255, 255));
        RecourceHubExplanationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourceHubExplanationLabel.setText("A hub were users can upload, organize");

        javax.swing.GroupLayout HomePagePanelLayout = new javax.swing.GroupLayout(HomePagePanel);
        HomePagePanel.setLayout(HomePagePanelLayout);
        HomePagePanelLayout.setHorizontalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePagePanelLayout.createSequentialGroup()
                .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(ReportGeneratorLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RecourceHubLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePagePanelLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(ReportGeneratorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HomePagePanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(ReportGeneratorExplanationLabel)))
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePagePanelLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(RecourceHubLabel))
                            .addGroup(HomePagePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(RecourceHubExplanationLabel))))
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(ReportGeneratorExplanationLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RecourceHubExplanationLabel1)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        HomePagePanelLayout.setVerticalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePagePanelLayout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addComponent(ReportGeneratorLogoLabel)
                        .addGap(22, 22, 22)
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReportGeneratorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecourceHubLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addComponent(RecourceHubLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportGeneratorExplanationLabel)
                    .addComponent(RecourceHubExplanationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportGeneratorExplanationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecourceHubExplanationLabel1))
                .addGap(146, 146, 146))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecourceHubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecourceHubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecourceHubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecourceHubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecourceHubGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePagePanel;
    private javax.swing.JLabel RecourceHubExplanationLabel;
    private javax.swing.JLabel RecourceHubExplanationLabel1;
    private javax.swing.JLabel RecourceHubLabel;
    private javax.swing.JLabel RecourceHubLogoLabel;
    private javax.swing.JLabel ReportGeneratorExplanationLabel;
    private javax.swing.JLabel ReportGeneratorExplanationLabel1;
    private javax.swing.JLabel ReportGeneratorLabel;
    private javax.swing.JLabel ReportGeneratorLogoLabel;
    // End of variables declaration//GEN-END:variables
}
