/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grantmanagementsystem;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList; // For ArrayList
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.ArrayList;


/**
 *
 * @author gregm
 */
public class StudentInformationGUIKarawan extends javax.swing.JFrame {

    /**
     * Creates new form StudentInformationGUIKarawan
     */
    public StudentInformationGUIKarawan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        studentPNL1 = new javax.swing.JPanel();
        StudentPanel = new javax.swing.JPanel();
        studentLBL1 = new javax.swing.JLabel();
        nameLBL1 = new javax.swing.JLabel();
        studentTF1 = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        levelLBL1 = new javax.swing.JLabel();
        contactLBL1 = new javax.swing.JLabel();
        levelTF1 = new javax.swing.JTextField();
        contactTF1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTBL = new javax.swing.JTable();
        enrollBTN = new javax.swing.JButton();
        viewBTN = new javax.swing.JButton();
        applyBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        coursenameLBL1 = new javax.swing.JLabel();
        coursenameTF1 = new javax.swing.JTextField();
        CoursesPNL = new javax.swing.JPanel();
        CoursePanel = new javax.swing.JPanel();
        CourseID = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        CourseName2 = new javax.swing.JLabel();
        CourseNameField = new javax.swing.JTextField();
        CourseLevel = new javax.swing.JLabel();
        MaxCapicity = new javax.swing.JLabel();
        CourseLevelField = new javax.swing.JTextField();
        MaxField = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        AddButton1 = new javax.swing.JButton();
        ViewButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CourseTable = new javax.swing.JTable();
        StudentGrowth = new javax.swing.JPanel();
        StudentGrowthPanel = new javax.swing.JPanel();
        TotalButton = new javax.swing.JButton();
        LowestLabel = new javax.swing.JLabel();
        LowestField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AverageField = new javax.swing.JTextField();
        HighestLabel = new javax.swing.JLabel();
        HighestField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jTabbedPane1.setBackground(new java.awt.Color(51, 204, 255));

        studentPNL1.setBackground(new java.awt.Color(51, 204, 255));
        studentPNL1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        StudentPanel.setBackground(new java.awt.Color(51, 204, 255));

        studentLBL1.setText("Student ID");

        nameLBL1.setText("Name");

        levelLBL1.setText("Level");

        contactLBL1.setText("Contact info");

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentTF1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(Name))
                .addGap(87, 87, 87)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(levelLBL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactLBL1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(levelTF1)
                    .addComponent(contactTF1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentLBL1)
                    .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(levelLBL1)
                        .addComponent(levelTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLBL1)
                    .addComponent(contactTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        studentTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Course Name", "Level", "Contact Info"
            }
        ));
        jScrollPane1.setViewportView(studentTBL);

        enrollBTN.setText("Enroll Student");
        enrollBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollBTNActionPerformed(evt);
            }
        });

        viewBTN.setText("View Academic Record");
        viewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBTNActionPerformed(evt);
            }
        });

        applyBTN.setText("Apply for Aid");
        applyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("Delete Record");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        coursenameLBL1.setText("Course Name");

        javax.swing.GroupLayout studentPNL1Layout = new javax.swing.GroupLayout(studentPNL1);
        studentPNL1.setLayout(studentPNL1Layout);
        studentPNL1Layout.setHorizontalGroup(
            studentPNL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPNL1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPNL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(studentPNL1Layout.createSequentialGroup()
                        .addComponent(enrollBTN)
                        .addGap(18, 18, 18)
                        .addComponent(viewBTN)
                        .addGap(28, 28, 28)
                        .addComponent(applyBTN)
                        .addGap(26, 26, 26)
                        .addComponent(deleteBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBTN)
                        .addGap(9, 9, 9))
                    .addGroup(studentPNL1Layout.createSequentialGroup()
                        .addComponent(coursenameLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(coursenameTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(studentPNL1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentPNL1Layout.setVerticalGroup(
            studentPNL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPNL1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPNL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coursenameLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coursenameTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentPNL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPNL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enrollBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(applyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Students", studentPNL1);

        CoursePanel.setBackground(new java.awt.Color(0, 204, 255));

        CourseID.setText("CourseID");

        CourseName2.setText("CourseName");

        CourseLevel.setText("CourseLevel");

        MaxCapicity.setText("MaxCapicity");

        DeleteButton.setText("Delete Course");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        AddButton1.setText("Enroll Course");
        AddButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButton1ActionPerformed(evt);
            }
        });

        ViewButton.setText("View Courses");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        CourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CourseID", "CourseName", "MaxCapicity", "CourseLevel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(CourseTable);

        javax.swing.GroupLayout CoursePanelLayout = new javax.swing.GroupLayout(CoursePanel);
        CoursePanel.setLayout(CoursePanelLayout);
        CoursePanelLayout.setHorizontalGroup(
            CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CoursePanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CoursePanelLayout.createSequentialGroup()
                                .addComponent(MaxCapicity, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CoursePanelLayout.createSequentialGroup()
                                .addComponent(CourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CoursePanelLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(CourseName2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoursePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CourseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CourseNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(CourseLevelField)))
                    .addGroup(CoursePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        CoursePanelLayout.setVerticalGroup(
            CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoursePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseName2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaxCapicity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton1)
                    .addComponent(ViewButton)
                    .addComponent(DeleteButton)
                    .addComponent(ExitButton))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout CoursesPNLLayout = new javax.swing.GroupLayout(CoursesPNL);
        CoursesPNL.setLayout(CoursesPNLLayout);
        CoursesPNLLayout.setHorizontalGroup(
            CoursesPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoursePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CoursesPNLLayout.setVerticalGroup(
            CoursesPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoursePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Courses", CoursesPNL);

        StudentGrowthPanel.setBackground(new java.awt.Color(0, 204, 255));

        TotalButton.setText("Total");

        LowestLabel.setText("Lowest");

        jLabel1.setText("Average");

        HighestLabel.setText("Highest");

        javax.swing.GroupLayout StudentGrowthPanelLayout = new javax.swing.GroupLayout(StudentGrowthPanel);
        StudentGrowthPanel.setLayout(StudentGrowthPanelLayout);
        StudentGrowthPanelLayout.setHorizontalGroup(
            StudentGrowthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentGrowthPanelLayout.createSequentialGroup()
                .addGroup(StudentGrowthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentGrowthPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(StudentGrowthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(StudentGrowthPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AverageField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentGrowthPanelLayout.createSequentialGroup()
                                .addComponent(LowestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LowestField)))
                        .addGap(75, 75, 75)
                        .addComponent(HighestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HighestField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentGrowthPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(TotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );
        StudentGrowthPanelLayout.setVerticalGroup(
            StudentGrowthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentGrowthPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(StudentGrowthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AverageField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HighestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HighestField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addGroup(StudentGrowthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LowestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LowestField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(TotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout StudentGrowthLayout = new javax.swing.GroupLayout(StudentGrowth);
        StudentGrowth.setLayout(StudentGrowthLayout);
        StudentGrowthLayout.setHorizontalGroup(
            StudentGrowthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentGrowthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 758, Short.MAX_VALUE)
        );
        StudentGrowthLayout.setVerticalGroup(
            StudentGrowthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentGrowthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Student growth", StudentGrowth);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollBTNActionPerformed
        // TODO add your handling code here:

        File inFile = new File("studentData.txt");

        try (BufferedReader br = new BufferedReader(new FileReader(inFile))) {
            // Get the table model from the studentTBL
            DefaultTableModel tableModel = (DefaultTableModel) studentTBL.getModel();

            // Clear existing rows in case of reload
            tableModel.setRowCount(0);

            String line;
            while ((line = br.readLine()) != null) {
                // Split the line into columns using the comma delimiter
                String[] rowData = line.split(",");

                // Ensure the number of columns in the file matches the table's structure
                if (rowData.length == tableModel.getColumnCount()) {
                    tableModel.addRow(rowData);
                } else {
                    JOptionPane.showMessageDialog(null,
                        "Mismatch between file columns and table columns.\nCheck the file format.",
                        "Data Error",
                        JOptionPane.WARNING_MESSAGE);
                    break;
                }
            }
        } catch (IOException ex) {
            // Show an error dialog if there's an issue reading the file
            JOptionPane.showMessageDialog(null,
                "Error reading file: " + ex.getMessage(),
                "File Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enrollBTNActionPerformed

    private void viewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBTNActionPerformed

        File inFile = new File("studentData.txt");

        try (BufferedReader br = new BufferedReader(new FileReader(inFile))) {
            // Get the table model from the studentTBL
            DefaultTableModel tableModel = (DefaultTableModel) studentTBL.getModel();

            // Clear existing rows in case of reload
            tableModel.setRowCount(0);

            String line;
            while ((line = br.readLine()) != null) {
                // Split the line into columns using the comma delimiter
                String[] rowData = line.split(",");

                // Ensure the number of columns in the file matches the table's structure
                if (rowData.length == tableModel.getColumnCount()) {
                    tableModel.addRow(rowData);
                } else {
                    JOptionPane.showMessageDialog(null,
                        "Mismatch between file columns and table columns.\nCheck the file format.",
                        "Data Error",
                        JOptionPane.WARNING_MESSAGE);
                    break;
                }
            }
        } catch (IOException ex) {
            // Show an error dialog if there's an issue reading the file
            JOptionPane.showMessageDialog(null,
                "Error reading file: " + ex.getMessage(),
                "File Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        setVisible(false);

        // Open the HomePage
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
   // Assuming you have a JTable called studentTBL and a Delete button (deleteBTN)

deleteBTN.addActionListener(e -> {
    // Get the selected row from the table
    int selectedRow = studentTBL.getSelectedRow();

    if (selectedRow != -1) {  // Check if a row is selected
        // Confirm the delete action
        int confirmation = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to delete this record?",
            "Delete Confirmation",
            JOptionPane.YES_NO_OPTION);

        if (confirmation == JOptionPane.YES_OPTION) {
            // Remove the selected row from the table
            DefaultTableModel tableModel = (DefaultTableModel) studentTBL.getModel();
            tableModel.removeRow(selectedRow);

            // Now update the file (studentData.txt)
            File inFile = new File("studentData.txt");
            File tempFile = new File("studentData_temp.txt");

            try (BufferedReader br = new BufferedReader(new FileReader(inFile));
                 BufferedWriter bw = new BufferedWriter(new FileWriter(tempFile))) {

                String line;
                int lineIndex = 0;

                // Loop through the file and write all data except the deleted row
                while ((line = br.readLine()) != null) {
                    // Split the line into columns
                    String[] rowData = line.split(",");

                    // If the current row is not the deleted one, write it back to the file
                    if (lineIndex != selectedRow) {
                        bw.write(line);
                        bw.newLine();
                    }
                    lineIndex++;
                }

                // Rename the temp file to the original file
                if (inFile.delete()) {
                    tempFile.renameTo(inFile);
                }

            } catch (IOException ex) {
                // Show an error dialog if there's an issue reading or writing the file
                JOptionPane.showMessageDialog(null,
                    "Error updating file: " + ex.getMessage(),
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        // No row selected, show a message
        JOptionPane.showMessageDialog(null,
            "Please select a student to delete.",
            "No Selection",
            JOptionPane.WARNING_MESSAGE);
    }
});

    }//GEN-LAST:event_deleteBTNActionPerformed

    private void applyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBTNActionPerformed
        // TODO add your handling code here:
          new FinancialAidGUIShoaib().setVisible(true);
                dispose(); // Close current frame
    }//GEN-LAST:event_applyBTNActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
               File inFile = new File("CourseData.txt");

        try (BufferedReader br = new BufferedReader(new FileReader(inFile))) {
            // Get the table model from the studentTBL
            DefaultTableModel tableModel = (DefaultTableModel) CourseTable.getModel();

            // Clear existing rows in case of reload
            tableModel.setRowCount(0);

            String line;
            while ((line = br.readLine()) != null) {
                // Split the line into columns using the comma delimiter
                String[] rowData = line.split(",");
                
                 //Ensure the number of columns in the file matches the table's structure
                if (rowData.length == tableModel.getColumnCount()) {
                    tableModel.addRow(rowData);//problem 
                } else {
                    JOptionPane.showMessageDialog(null,
                        "Mismatch between file columns and table columns.\nCheck the file format.",
                        "Data Error",
                        JOptionPane.WARNING_MESSAGE);
                    break;
                }
            }
            
        } catch (IOException ex) {
            // Show an error dialog if there's an issue reading the file
            JOptionPane.showMessageDialog(null,
                "Error reading file: " + ex.getMessage(),
                "File Error",
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ViewButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed

        System.exit(0);

    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AddButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButton1ActionPerformed
        // TODO add your handling code here:
         File inFile = new File("coursedata.txt");

        try (BufferedReader br = new BufferedReader(new FileReader(inFile))) {
            // Get the table model from the studentTBL
            DefaultTableModel tableModel = (DefaultTableModel) CourseTable.getModel();

            // Clear existing rows in case of reload
            tableModel.setRowCount(0);

            String line;
            while ((line = br.readLine()) != null) {
                // Split the line into columns using the comma delimiter
                String[] rowData = line.split(",");

                // Ensure the number of columns in the file matches the table's structure
                if (rowData.length == tableModel.getColumnCount()) {
                    tableModel.addRow(rowData);
                } else {
                    JOptionPane.showMessageDialog(null,
                        "Mismatch between file columns and table columns.\nCheck the file format.",
                        "Data Error",
                        JOptionPane.WARNING_MESSAGE);
                    break;
                }
            }
        } catch (IOException ex) {
            // Show an error dialog if there's an issue reading the file
            JOptionPane.showMessageDialog(null,
                "Error reading file: " + ex.getMessage(),
                "File Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddButton1ActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        DeleteButton.addActionListener(e -> {
    // Get the selected row from the course table
    int selectedRow = CourseTable.getSelectedRow();

    if (selectedRow != -1) {  // Check if a row is selected
        // Confirm the delete action
        int confirmation = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to delete this course record?",
            "Delete Confirmation",
            JOptionPane.YES_NO_OPTION);

        if (confirmation == JOptionPane.YES_OPTION) {
            // Remove the selected row from the table
            DefaultTableModel tableModel = (DefaultTableModel) CourseTable.getModel();
            tableModel.removeRow(selectedRow);

            // Now update the file (courseData.txt)
            File inFile = new File("coursedata.txt");
            File tempFile = new File("courseData_temp.txt");

            try (BufferedReader br = new BufferedReader(new FileReader(inFile));
                 BufferedWriter bw = new BufferedWriter(new FileWriter(tempFile))) {

                String line;
                int lineIndex = 0;

                // Loop through the file and write all data except the deleted row
                while ((line = br.readLine()) != null) {
                    // Split the line into columns
                    String[] rowData = line.split(",");

                    // If the current row is not the deleted one, write it back to the file
                    if (lineIndex != selectedRow) {
                        bw.write(line);
                        bw.newLine();
                    }
                    lineIndex++;
                }

                // Rename the temp file to the original file
                if (inFile.delete()) {
                    tempFile.renameTo(inFile);
                }

            } catch (IOException ex) {
                // Show an error dialog if there's an issue reading or writing the file
                JOptionPane.showMessageDialog(null,
                    "Error updating file: " + ex.getMessage(),
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        // No row selected, show a message
        JOptionPane.showMessageDialog(null,
            "Please select a course to delete.",
            "No Selection",
            JOptionPane.WARNING_MESSAGE);
    }
});

    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInformationGUIKarawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInformationGUIKarawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInformationGUIKarawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInformationGUIKarawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInformationGUIKarawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton1;
    private javax.swing.JTextField AverageField;
    private javax.swing.JLabel CourseID;
    private javax.swing.JLabel CourseLevel;
    private javax.swing.JTextField CourseLevelField;
    private javax.swing.JLabel CourseName2;
    private javax.swing.JTextField CourseNameField;
    private javax.swing.JPanel CoursePanel;
    private javax.swing.JTable CourseTable;
    private javax.swing.JPanel CoursesPNL;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField HighestField;
    private javax.swing.JLabel HighestLabel;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField LowestField;
    private javax.swing.JLabel LowestLabel;
    private javax.swing.JLabel MaxCapicity;
    private javax.swing.JTextField MaxField;
    private javax.swing.JTextField Name;
    private javax.swing.JPanel StudentGrowth;
    private javax.swing.JPanel StudentGrowthPanel;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JButton TotalButton;
    private javax.swing.JButton ViewButton;
    private javax.swing.JButton applyBTN;
    private javax.swing.JLabel contactLBL1;
    private javax.swing.JTextField contactTF1;
    private javax.swing.JLabel coursenameLBL1;
    private javax.swing.JTextField coursenameTF1;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton enrollBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel levelLBL1;
    private javax.swing.JTextField levelTF1;
    private javax.swing.JLabel nameLBL1;
    private javax.swing.JLabel studentLBL1;
    private javax.swing.JPanel studentPNL1;
    private javax.swing.JTable studentTBL;
    private javax.swing.JTextField studentTF1;
    private javax.swing.JButton viewBTN;
    // End of variables declaration//GEN-END:variables
}
