/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grantmanagementsystem;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gregm
 */
public class WarmEducationalEnviormentGUIGregory extends javax.swing.JFrame {

    /**
     * Creates new form RecourceHubGUI
     */
    public WarmEducationalEnviormentGUIGregory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePagePanel = new javax.swing.JPanel();
        ReportGeneratorLogoLabel = new javax.swing.JLabel();
        ReportGeneratorLabel = new javax.swing.JLabel();
        RecourceHubLogoLabel = new javax.swing.JLabel();
        RecourceHubLabel = new javax.swing.JLabel();
        ContactUsLogoLabel = new javax.swing.JLabel();
        ContactUsLabel = new javax.swing.JLabel();
        Parent = new javax.swing.JPanel();
        RecourceHubPNL = new javax.swing.JPanel();
        RecourceHubNavPNL = new javax.swing.JPanel();
        ManageRecourceLabel = new javax.swing.JLabel();
        QuizLabel = new javax.swing.JLabel();
        TutorialLabel = new javax.swing.JLabel();
        ReportGeneratorLabel1 = new javax.swing.JLabel();
        ReportGeneratorLabel2 = new javax.swing.JLabel();
        ReportGeneratorLabel3 = new javax.swing.JLabel();
        SecondParent = new javax.swing.JPanel();
        ManageRecourcesPNL = new javax.swing.JPanel();
        RecourceFirstNameLabel = new javax.swing.JLabel();
        RecourseFirstNameField = new javax.swing.JTextField();
        RecourseSurnameField = new javax.swing.JTextField();
        RecourcesSurnameLabel = new javax.swing.JLabel();
        RecourseTypeLabel = new javax.swing.JLabel();
        RecourseDateField = new javax.swing.JTextField();
        RecourseDateLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RecourseTBL = new javax.swing.JTable();
        URLLabel = new javax.swing.JLabel();
        RecourseURLField = new javax.swing.JTextField();
        CourseLabel = new javax.swing.JLabel();
        RecourseCourseField = new javax.swing.JTextField();
        SaveRecourseBTN = new javax.swing.JButton();
        ViewRecourceBTN = new javax.swing.JButton();
        RecourceTypeComboBox = new javax.swing.JComboBox<>();
        exitBTn = new javax.swing.JButton();
        TutorialsPNL = new javax.swing.JPanel();
        TutorialLabel2 = new javax.swing.JLabel();
        TutorialLabel3 = new javax.swing.JLabel();
        TutorialLabel5 = new javax.swing.JLabel();
        TutorialLabel4 = new javax.swing.JLabel();
        Tutorial1Label = new javax.swing.JLabel();
        TutorialNameLabel = new javax.swing.JLabel();
        TutorialNameLabel2 = new javax.swing.JLabel();
        TutorialNameLabel3 = new javax.swing.JLabel();
        TutorialNameLabel4 = new javax.swing.JLabel();
        TutorialNameLabel5 = new javax.swing.JLabel();
        exitBTn1 = new javax.swing.JButton();
        QuizPNL = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        ComputersQuizPNL = new javax.swing.JPanel();
        ComputersQuestionLabel2 = new javax.swing.JLabel();
        ComputersQuestionLabel1 = new javax.swing.JLabel();
        ComputersQuestionLabel3 = new javax.swing.JLabel();
        ComputersQuestionLabel4 = new javax.swing.JLabel();
        ComputersQuestionLabel5 = new javax.swing.JLabel();
        ComputerQuizComboBox = new javax.swing.JComboBox<>();
        ComputerQuizComboBox3 = new javax.swing.JComboBox<>();
        ComputerQuizComboBox2 = new javax.swing.JComboBox<>();
        ComputerQuizComboBox4 = new javax.swing.JComboBox<>();
        ComputerQuizComboBox5 = new javax.swing.JComboBox<>();
        ComputersClearBTN = new javax.swing.JButton();
        ComputersQuizCheckBTN = new javax.swing.JButton();
        exitBTn2 = new javax.swing.JButton();
        GeographyQuizPNL = new javax.swing.JPanel();
        GeographyQuizCheckBTN = new javax.swing.JButton();
        GeographyQuestionLabel1 = new javax.swing.JLabel();
        GeographyQuestionLabel2 = new javax.swing.JLabel();
        GeographyQuestionLabel3 = new javax.swing.JLabel();
        GeographyQuestionLabel4 = new javax.swing.JLabel();
        GeographyQuestionLabel5 = new javax.swing.JLabel();
        GeographyClearBTN1 = new javax.swing.JButton();
        GeographyQuizComboBox5 = new javax.swing.JComboBox<>();
        GeographyQuizComboBox4 = new javax.swing.JComboBox<>();
        GeographyQuizComboBox3 = new javax.swing.JComboBox<>();
        GeographyQuizComboBox2 = new javax.swing.JComboBox<>();
        GeographyQuizComboBox = new javax.swing.JComboBox<>();
        exitBTn3 = new javax.swing.JButton();
        ProgrammingQuizPNL = new javax.swing.JPanel();
        ProgrammingQuizCheckBTN = new javax.swing.JButton();
        ProgrammingClearBTN = new javax.swing.JButton();
        ProgrammingQuestionLabel5 = new javax.swing.JLabel();
        ProgrammingQuestionLabel4 = new javax.swing.JLabel();
        ProgrammingQuestionLabel3 = new javax.swing.JLabel();
        ProgrammingQuestionLabel2 = new javax.swing.JLabel();
        ProgrammingQuestionLabel1 = new javax.swing.JLabel();
        ProgrammingComboBox = new javax.swing.JComboBox<>();
        ProgrammingComboBox2 = new javax.swing.JComboBox<>();
        ProgrammingComboBox3 = new javax.swing.JComboBox<>();
        ProgrammingComboBox4 = new javax.swing.JComboBox<>();
        ProgrammingComboBox5 = new javax.swing.JComboBox<>();
        exitBTn4 = new javax.swing.JButton();
        ReportGeneratorPNL = new javax.swing.JPanel();
        FirstNameLabel = new javax.swing.JLabel();
        SurnameLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        SurnameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        ContentLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ContentTextArea = new javax.swing.JTextArea();
        SaveBTN = new javax.swing.JButton();
        ViewBTN = new javax.swing.JButton();
        DeleteBTN = new javax.swing.JButton();
        DateFormattedField = new javax.swing.JFormattedTextField();
        ReportGeneratorTitleLabel = new javax.swing.JLabel();
        exitBTn6 = new javax.swing.JButton();
        ContactUsPNL = new javax.swing.JPanel();
        ContactUsTitleLabel = new javax.swing.JLabel();
        ContactUsFirstNameField = new javax.swing.JTextField();
        ContactUsFirstNameLabel = new javax.swing.JLabel();
        FeedbackLabel = new javax.swing.JLabel();
        FeedbackTextAreaScrollPane = new javax.swing.JScrollPane();
        FeedbackTextArea = new javax.swing.JTextArea();
        TermsAndConditionsLabel = new javax.swing.JLabel();
        TermsAndConditionsCheckBox = new javax.swing.JCheckBox();
        ReviewDateLabel = new javax.swing.JLabel();
        ReviewDateFormattedField = new javax.swing.JFormattedTextField();
        ContactUsSurnameLabel = new javax.swing.JLabel();
        ContactUsSurnameField = new javax.swing.JTextField();
        ContactUsEmailLabel = new javax.swing.JLabel();
        ContactUsEmailField = new javax.swing.JTextField();
        SendFeedbackBTN = new javax.swing.JButton();
        exitBTn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));

        HomePagePanel.setBackground(new java.awt.Color(51, 204, 255));
        HomePagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        HomePagePanel.setLayout(null);

        ReportGeneratorLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document.png"))); // NOI18N
        ReportGeneratorLogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportGeneratorLogoLabelMouseClicked(evt);
            }
        });
        HomePagePanel.add(ReportGeneratorLogoLabel);
        ReportGeneratorLogoLabel.setBounds(30, 30, 70, 70);

        ReportGeneratorLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        ReportGeneratorLabel.setForeground(new java.awt.Color(255, 255, 255));
        ReportGeneratorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorLabel.setText("Report Generator");
        HomePagePanel.add(ReportGeneratorLabel);
        ReportGeneratorLabel.setBounds(10, 100, 100, 24);

        RecourceHubLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourceHubLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book.png"))); // NOI18N
        RecourceHubLogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecourceHubLogoLabelMouseClicked(evt);
            }
        });
        HomePagePanel.add(RecourceHubLogoLabel);
        RecourceHubLogoLabel.setBounds(20, 210, 80, 70);

        RecourceHubLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        RecourceHubLabel.setForeground(new java.awt.Color(255, 255, 255));
        RecourceHubLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourceHubLabel.setText("Recource hub");
        HomePagePanel.add(RecourceHubLabel);
        RecourceHubLabel.setBounds(10, 280, 100, 18);

        ContactUsLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactUsLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/communicate.png"))); // NOI18N
        ContactUsLogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactUsLogoLabelMouseClicked(evt);
            }
        });
        HomePagePanel.add(ContactUsLogoLabel);
        ContactUsLogoLabel.setBounds(20, 370, 80, 70);

        ContactUsLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        ContactUsLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactUsLabel.setText("Contact us");
        HomePagePanel.add(ContactUsLabel);
        ContactUsLabel.setBounds(20, 440, 70, 18);

        Parent.setBackground(new java.awt.Color(255, 255, 255));
        Parent.setLayout(new java.awt.CardLayout());

        RecourceHubPNL.setBackground(new java.awt.Color(51, 204, 255));
        RecourceHubPNL.setLayout(null);

        RecourceHubNavPNL.setBackground(new java.awt.Color(51, 204, 255));
        RecourceHubNavPNL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        ManageRecourceLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coordinator.png"))); // NOI18N
        ManageRecourceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageRecourceLabelMouseClicked(evt);
            }
        });

        QuizLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/choose.png"))); // NOI18N
        QuizLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuizLabelMouseClicked(evt);
            }
        });

        TutorialLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/educational-video.png"))); // NOI18N
        TutorialLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TutorialLabelMouseClicked(evt);
            }
        });

        ReportGeneratorLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        ReportGeneratorLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ReportGeneratorLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorLabel1.setText("Tutorials");

        ReportGeneratorLabel2.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        ReportGeneratorLabel2.setForeground(new java.awt.Color(255, 255, 255));
        ReportGeneratorLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorLabel2.setText("Manage recources");

        ReportGeneratorLabel3.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        ReportGeneratorLabel3.setForeground(new java.awt.Color(255, 255, 255));
        ReportGeneratorLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorLabel3.setText("Quiz");

        javax.swing.GroupLayout RecourceHubNavPNLLayout = new javax.swing.GroupLayout(RecourceHubNavPNL);
        RecourceHubNavPNL.setLayout(RecourceHubNavPNLLayout);
        RecourceHubNavPNLLayout.setHorizontalGroup(
            RecourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecourceHubNavPNLLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(RecourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RecourceHubNavPNLLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(TutorialLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QuizLabel)
                        .addGap(129, 129, 129)
                        .addComponent(ManageRecourceLabel)
                        .addGap(126, 126, 126))
                    .addGroup(RecourceHubNavPNLLayout.createSequentialGroup()
                        .addComponent(ReportGeneratorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(ReportGeneratorLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(ReportGeneratorLabel2)
                        .addGap(104, 104, 104))))
        );
        RecourceHubNavPNLLayout.setVerticalGroup(
            RecourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecourceHubNavPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RecourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QuizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RecourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TutorialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ManageRecourceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RecourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportGeneratorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReportGeneratorLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReportGeneratorLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        RecourceHubPNL.add(RecourceHubNavPNL);
        RecourceHubNavPNL.setBounds(0, 0, 690, 130);

        SecondParent.setLayout(new java.awt.CardLayout());

        ManageRecourcesPNL.setBackground(new java.awt.Color(51, 204, 255));
        ManageRecourcesPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RecourceFirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourceFirstNameLabel.setText("FirstName");
        ManageRecourcesPNL.add(RecourceFirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 9, 56, -1));
        ManageRecourcesPNL.add(RecourseFirstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 6, 101, -1));

        RecourseSurnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecourseSurnameFieldActionPerformed(evt);
            }
        });
        ManageRecourcesPNL.add(RecourseSurnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 6, 101, -1));

        RecourcesSurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourcesSurnameLabel.setText("Surname");
        ManageRecourcesPNL.add(RecourcesSurnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 9, 50, -1));

        RecourseTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourseTypeLabel.setText("RecourceType");
        ManageRecourcesPNL.add(RecourseTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 49, 75, -1));
        ManageRecourcesPNL.add(RecourseDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 46, 101, -1));

        RecourseDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourseDateLabel.setText("Date");
        ManageRecourcesPNL.add(RecourseDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 50, -1));

        RecourseTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FirstName", "Surname", "Date", "Type", "URL", "Course"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(RecourseTBL);

        ManageRecourcesPNL.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 167, 636, 166));

        URLLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        URLLabel.setText("URL");
        ManageRecourcesPNL.add(URLLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 50, -1));
        ManageRecourcesPNL.add(RecourseURLField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 86, 101, -1));

        CourseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CourseLabel.setText("Course");
        ManageRecourcesPNL.add(CourseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 89, 50, -1));
        ManageRecourcesPNL.add(RecourseCourseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 86, 101, -1));

        SaveRecourseBTN.setText("Save");
        SaveRecourseBTN.setMaximumSize(new java.awt.Dimension(72, 22));
        SaveRecourseBTN.setMinimumSize(new java.awt.Dimension(72, 22));
        SaveRecourseBTN.setPreferredSize(new java.awt.Dimension(72, 22));
        SaveRecourseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveRecourseBTNActionPerformed(evt);
            }
        });
        ManageRecourcesPNL.add(SaveRecourseBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 75, -1));

        ViewRecourceBTN.setText("View");
        ViewRecourceBTN.setMaximumSize(new java.awt.Dimension(72, 22));
        ViewRecourceBTN.setMinimumSize(new java.awt.Dimension(72, 22));
        ViewRecourceBTN.setPreferredSize(new java.awt.Dimension(72, 22));
        ViewRecourceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRecourceBTNActionPerformed(evt);
            }
        });
        ManageRecourcesPNL.add(ViewRecourceBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 80, -1));

        RecourceTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Website", "Video", "Tutorial", "Book", " " }));
        ManageRecourcesPNL.add(RecourceTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 110, 20));

        exitBTn.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn.setText("EXIT");
        exitBTn.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTnActionPerformed(evt);
            }
        });
        ManageRecourcesPNL.add(exitBTn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 70, -1));

        SecondParent.add(ManageRecourcesPNL, "card4");

        TutorialsPNL.setBackground(new java.awt.Color(51, 204, 255));

        TutorialLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-lesson.png"))); // NOI18N

        TutorialLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-lesson.png"))); // NOI18N

        TutorialLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-lesson.png"))); // NOI18N

        TutorialLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-lesson.png"))); // NOI18N

        Tutorial1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tutorial1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-lesson.png"))); // NOI18N

        TutorialNameLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        TutorialNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialNameLabel.setText("Tutorial 1");

        TutorialNameLabel2.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        TutorialNameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialNameLabel2.setText("Tutorial 2");

        TutorialNameLabel3.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        TutorialNameLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialNameLabel3.setText("Tutorial 3");

        TutorialNameLabel4.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        TutorialNameLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialNameLabel4.setText("Tutorial 4");

        TutorialNameLabel5.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        TutorialNameLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialNameLabel5.setText("Tutorial 5");

        exitBTn1.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn1.setText("EXIT");
        exitBTn1.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn1.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn1.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TutorialsPNLLayout = new javax.swing.GroupLayout(TutorialsPNL);
        TutorialsPNL.setLayout(TutorialsPNLLayout);
        TutorialsPNLLayout.setHorizontalGroup(
            TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialsPNLLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TutorialsPNLLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(TutorialNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(TutorialNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TutorialNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(TutorialsPNLLayout.createSequentialGroup()
                        .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TutorialsPNLLayout.createSequentialGroup()
                                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tutorial1Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TutorialLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TutorialLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TutorialLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addComponent(TutorialLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TutorialsPNLLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(exitBTn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(TutorialsPNLLayout.createSequentialGroup()
                                        .addComponent(TutorialNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(143, 143, 143)
                                        .addComponent(TutorialNameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(100, Short.MAX_VALUE))))
        );
        TutorialsPNLLayout.setVerticalGroup(
            TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialsPNLLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TutorialLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TutorialLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tutorial1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TutorialNameLabel)
                        .addComponent(TutorialNameLabel2))
                    .addComponent(TutorialNameLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TutorialLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TutorialLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TutorialNameLabel4)
                    .addComponent(TutorialNameLabel5))
                .addGap(18, 18, 18)
                .addComponent(exitBTn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        SecondParent.add(TutorialsPNL, "card2");

        QuizPNL.setBackground(new java.awt.Color(51, 204, 255));

        jTabbedPane3.setBackground(new java.awt.Color(51, 204, 255));

        ComputersQuizPNL.setBackground(new java.awt.Color(51, 204, 255));

        ComputersQuestionLabel2.setText("What does \"PSU\" stand for?");

        ComputersQuestionLabel1.setText("What is a CPU doing?");

        ComputersQuestionLabel3.setText("What is a M.2 used for?");

        ComputersQuestionLabel4.setText("What does \"SSD\" stand for?");

        ComputersQuestionLabel5.setText("What does \"GPU\" stand for?");

        ComputerQuizComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Central processing unit", "Cornered processing union", "Centrelised Power unit", "Cell processing unit", " ", " " }));

        ComputerQuizComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Storing data", "Loading graphics", "Executing instructions", "Supply power", " " }));

        ComputerQuizComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Power Shell Unit", "Power supply unit", "Primary suppy unit", "Perfect supply unit" }));

        ComputerQuizComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComputerQuizComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComputersClearBTN.setText("Clear ");
        ComputersClearBTN.setMaximumSize(new java.awt.Dimension(72, 22));
        ComputersClearBTN.setMinimumSize(new java.awt.Dimension(72, 22));
        ComputersClearBTN.setPreferredSize(new java.awt.Dimension(72, 22));

        ComputersQuizCheckBTN.setText("Check");
        ComputersQuizCheckBTN.setMaximumSize(new java.awt.Dimension(72, 22));
        ComputersQuizCheckBTN.setMinimumSize(new java.awt.Dimension(72, 22));
        ComputersQuizCheckBTN.setPreferredSize(new java.awt.Dimension(72, 22));
        ComputersQuizCheckBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputersQuizCheckBTNActionPerformed(evt);
            }
        });

        exitBTn2.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn2.setText("EXIT");
        exitBTn2.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn2.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn2.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ComputersQuizPNLLayout = new javax.swing.GroupLayout(ComputersQuizPNL);
        ComputersQuizPNL.setLayout(ComputersQuizPNLLayout);
        ComputersQuizPNLLayout.setHorizontalGroup(
            ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersQuizPNLLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ComputersQuizPNLLayout.createSequentialGroup()
                        .addComponent(ComputersQuestionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComputerQuizComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(403, 403, 403))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ComputersQuizPNLLayout.createSequentialGroup()
                        .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ComputersQuizPNLLayout.createSequentialGroup()
                                .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ComputersQuestionLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComputersQuestionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComputersQuestionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComputersQuestionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComputersQuizPNLLayout.createSequentialGroup()
                                .addComponent(ComputersClearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ComputersQuizPNLLayout.createSequentialGroup()
                                .addComponent(ComputersQuizCheckBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(exitBTn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ComputerQuizComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ComputerQuizComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ComputerQuizComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ComputerQuizComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ComputersQuizPNLLayout.setVerticalGroup(
            ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputersQuizPNLLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComputersQuestionLabel1)
                    .addComponent(ComputerQuizComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComputersQuestionLabel2)
                    .addComponent(ComputerQuizComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComputersQuestionLabel3)
                    .addComponent(ComputerQuizComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComputersQuestionLabel4)
                    .addComponent(ComputerQuizComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComputersQuestionLabel5)
                    .addComponent(ComputerQuizComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(ComputersQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComputersClearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComputersQuizCheckBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBTn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jTabbedPane3.addTab("Computers quiz", ComputersQuizPNL);

        GeographyQuizPNL.setBackground(new java.awt.Color(51, 204, 255));

        GeographyQuizCheckBTN.setText("Check");
        GeographyQuizCheckBTN.setMaximumSize(new java.awt.Dimension(72, 22));
        GeographyQuizCheckBTN.setMinimumSize(new java.awt.Dimension(72, 22));
        GeographyQuizCheckBTN.setPreferredSize(new java.awt.Dimension(72, 22));

        GeographyQuestionLabel1.setText("What is the capital of China?");

        GeographyQuestionLabel2.setText("What is the capital of Turkey?");

        GeographyQuestionLabel3.setText("What is the capital of Ireland?");

        GeographyQuestionLabel4.setText("Which continent is the largest?");

        GeographyQuestionLabel5.setText("Which one of these is not a continent?");

        GeographyClearBTN1.setText("Clear");
        GeographyClearBTN1.setMaximumSize(new java.awt.Dimension(72, 22));
        GeographyClearBTN1.setMinimumSize(new java.awt.Dimension(72, 22));
        GeographyClearBTN1.setPreferredSize(new java.awt.Dimension(72, 22));

        GeographyQuizComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GeographyQuizComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GeographyQuizComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GeographyQuizComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GeographyQuizComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        exitBTn3.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn3.setText("EXIT");
        exitBTn3.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn3.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn3.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GeographyQuizPNLLayout = new javax.swing.GroupLayout(GeographyQuizPNL);
        GeographyQuizPNL.setLayout(GeographyQuizPNLLayout);
        GeographyQuizPNLLayout.setHorizontalGroup(
            GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeographyQuizPNLLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(GeographyQuizPNLLayout.createSequentialGroup()
                        .addGroup(GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GeographyQuestionLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeographyQuestionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeographyQuestionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeographyQuestionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GeographyQuizComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeographyQuizComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeographyQuizComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeographyQuizComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GeographyQuizPNLLayout.createSequentialGroup()
                        .addComponent(GeographyQuestionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GeographyQuizComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(403, 403, 403))))
            .addGroup(GeographyQuizPNLLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(GeographyClearBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(GeographyQuizCheckBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(exitBTn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        GeographyQuizPNLLayout.setVerticalGroup(
            GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeographyQuizPNLLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeographyQuestionLabel1)
                    .addComponent(GeographyQuizComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeographyQuestionLabel2)
                    .addComponent(GeographyQuizComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeographyQuestionLabel3)
                    .addComponent(GeographyQuizComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeographyQuestionLabel4)
                    .addComponent(GeographyQuizComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeographyQuestionLabel5)
                    .addComponent(GeographyQuizComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(GeographyQuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeographyClearBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeographyQuizCheckBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBTn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jTabbedPane3.addTab("Geography quiz", GeographyQuizPNL);

        ProgrammingQuizPNL.setBackground(new java.awt.Color(51, 204, 255));
        ProgrammingQuizPNL.setLayout(null);

        ProgrammingQuizCheckBTN.setText("Check");
        ProgrammingQuizCheckBTN.setMaximumSize(new java.awt.Dimension(72, 22));
        ProgrammingQuizCheckBTN.setMinimumSize(new java.awt.Dimension(72, 22));
        ProgrammingQuizCheckBTN.setPreferredSize(new java.awt.Dimension(72, 22));
        ProgrammingQuizPNL.add(ProgrammingQuizCheckBTN);
        ProgrammingQuizCheckBTN.setBounds(260, 310, 72, 22);

        ProgrammingClearBTN.setText("Clear ");
        ProgrammingClearBTN.setMaximumSize(new java.awt.Dimension(72, 22));
        ProgrammingClearBTN.setMinimumSize(new java.awt.Dimension(72, 22));
        ProgrammingClearBTN.setPreferredSize(new java.awt.Dimension(72, 22));
        ProgrammingQuizPNL.add(ProgrammingClearBTN);
        ProgrammingClearBTN.setBounds(170, 310, 72, 22);

        ProgrammingQuestionLabel5.setText("Which one of these is not a continent?");
        ProgrammingQuizPNL.add(ProgrammingQuestionLabel5);
        ProgrammingQuestionLabel5.setBounds(21, 222, 275, 16);

        ProgrammingQuestionLabel4.setText("Which continent is the largest?");
        ProgrammingQuizPNL.add(ProgrammingQuestionLabel4);
        ProgrammingQuestionLabel4.setBounds(21, 182, 275, 16);

        ProgrammingQuestionLabel3.setText("What is the capital of Ireland?");
        ProgrammingQuizPNL.add(ProgrammingQuestionLabel3);
        ProgrammingQuestionLabel3.setBounds(21, 148, 275, 16);

        ProgrammingQuestionLabel2.setText("What is the capital of Turkey?");
        ProgrammingQuizPNL.add(ProgrammingQuestionLabel2);
        ProgrammingQuestionLabel2.setBounds(21, 108, 275, 16);

        ProgrammingQuestionLabel1.setText("What is the capital of China?");
        ProgrammingQuizPNL.add(ProgrammingQuestionLabel1);
        ProgrammingQuestionLabel1.setBounds(21, 68, 275, 16);

        ProgrammingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProgrammingQuizPNL.add(ProgrammingComboBox);
        ProgrammingComboBox.setBounds(302, 65, 228, 22);

        ProgrammingComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProgrammingQuizPNL.add(ProgrammingComboBox2);
        ProgrammingComboBox2.setBounds(302, 105, 228, 22);

        ProgrammingComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProgrammingQuizPNL.add(ProgrammingComboBox3);
        ProgrammingComboBox3.setBounds(302, 145, 228, 22);

        ProgrammingComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProgrammingQuizPNL.add(ProgrammingComboBox4);
        ProgrammingComboBox4.setBounds(302, 179, 228, 22);

        ProgrammingComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProgrammingQuizPNL.add(ProgrammingComboBox5);
        ProgrammingComboBox5.setBounds(302, 219, 228, 22);

        exitBTn4.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn4.setText("EXIT");
        exitBTn4.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn4.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn4.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTn4ActionPerformed(evt);
            }
        });
        ProgrammingQuizPNL.add(exitBTn4);
        exitBTn4.setBounds(350, 310, 72, 22);

        jTabbedPane3.addTab("Programming quiz", ProgrammingQuizPNL);

        javax.swing.GroupLayout QuizPNLLayout = new javax.swing.GroupLayout(QuizPNL);
        QuizPNL.setLayout(QuizPNLLayout);
        QuizPNLLayout.setHorizontalGroup(
            QuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizPNLLayout.createSequentialGroup()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        QuizPNLLayout.setVerticalGroup(
            QuizPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        SecondParent.add(QuizPNL, "card3");

        RecourceHubPNL.add(SecondParent);
        SecondParent.setBounds(0, 130, 690, 380);

        Parent.add(RecourceHubPNL, "card3");

        ReportGeneratorPNL.setBackground(new java.awt.Color(51, 204, 255));

        FirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FirstNameLabel.setText("First name");

        SurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SurnameLabel.setText("Surname");

        DateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateLabel.setText("Date");

        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmailLabel.setText("Email");

        FirstNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        SurnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SurnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurnameFieldActionPerformed(evt);
            }
        });

        EmailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        ContentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContentLabel.setText("Content");

        ContentTextArea.setColumns(20);
        ContentTextArea.setRows(5);
        jScrollPane1.setViewportView(ContentTextArea);

        SaveBTN.setText("save");

        ViewBTN.setText("view");

        DeleteBTN.setText("delete");

        DateFormattedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateFormattedFieldActionPerformed(evt);
            }
        });

        ReportGeneratorTitleLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        ReportGeneratorTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        ReportGeneratorTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorTitleLabel.setText("Report Generator");

        exitBTn6.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn6.setText("EXIT");
        exitBTn6.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn6.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn6.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportGeneratorPNLLayout = new javax.swing.GroupLayout(ReportGeneratorPNL);
        ReportGeneratorPNL.setLayout(ReportGeneratorPNLLayout);
        ReportGeneratorPNLLayout.setHorizontalGroup(
            ReportGeneratorPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportGeneratorPNLLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(ReportGeneratorPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ReportGeneratorPNLLayout.createSequentialGroup()
                        .addGroup(ReportGeneratorPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ReportGeneratorPNLLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ReportGeneratorPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportGeneratorPNLLayout.createSequentialGroup()
                                .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ReportGeneratorPNLLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ReportGeneratorPNLLayout.createSequentialGroup()
                        .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ReportGeneratorPNLLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(ContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addGap(113, 113, 113))
            .addGroup(ReportGeneratorPNLLayout.createSequentialGroup()
                .addGroup(ReportGeneratorPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportGeneratorPNLLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(ReportGeneratorTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReportGeneratorPNLLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(ViewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(exitBTn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReportGeneratorPNLLayout.setVerticalGroup(
            ReportGeneratorPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportGeneratorPNLLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ReportGeneratorTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ReportGeneratorPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReportGeneratorPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(SurnameLabel))
                .addGap(34, 34, 34)
                .addGroup(ReportGeneratorPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportGeneratorPNLLayout.createSequentialGroup()
                        .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailLabel))
                    .addGroup(ReportGeneratorPNLLayout.createSequentialGroup()
                        .addComponent(DateFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(ReportGeneratorPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBTN)
                    .addComponent(ViewBTN)
                    .addComponent(DeleteBTN)
                    .addComponent(exitBTn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        Parent.add(ReportGeneratorPNL, "card4");

        ContactUsPNL.setBackground(new java.awt.Color(51, 204, 255));

        ContactUsTitleLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        ContactUsTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactUsTitleLabel.setText("Contact Us");

        ContactUsFirstNameField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsFirstNameField.setToolTipText("Please enter your first name into this field.\n");
        ContactUsFirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactUsFirstNameFieldActionPerformed(evt);
            }
        });
        ContactUsFirstNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactUsFirstNameFieldKeyPressed(evt);
            }
        });

        ContactUsFirstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsFirstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsFirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactUsFirstNameLabel.setText("FirstName");

        FeedbackLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        FeedbackLabel.setForeground(new java.awt.Color(255, 255, 255));
        FeedbackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FeedbackLabel.setText("Feedback");

        FeedbackTextArea.setColumns(20);
        FeedbackTextArea.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        FeedbackTextArea.setRows(5);
        FeedbackTextArea.setToolTipText("Please enter your review into this text area on your experience with said component.");
        FeedbackTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FeedbackTextAreaKeyPressed(evt);
            }
        });
        FeedbackTextAreaScrollPane.setViewportView(FeedbackTextArea);

        TermsAndConditionsLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        TermsAndConditionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        TermsAndConditionsLabel.setText("Terms and conditions");

        TermsAndConditionsCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TermsAndConditionsCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        TermsAndConditionsCheckBox.setText("I Accept");
        TermsAndConditionsCheckBox.setToolTipText("Please accept the terms and conditions in order to submit a review.");

        ReviewDateLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ReviewDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        ReviewDateLabel.setText("ReviewDate");

        ReviewDateFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        ReviewDateFormattedField.setToolTipText("Please enter the date that the review is being submitted.");
        ReviewDateFormattedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewDateFormattedFieldActionPerformed(evt);
            }
        });
        ReviewDateFormattedField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ReviewDateFormattedFieldKeyPressed(evt);
            }
        });

        ContactUsSurnameLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsSurnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsSurnameLabel.setText("Surname");

        ContactUsSurnameField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsSurnameField.setToolTipText("Please enter your surname into this field.");
        ContactUsSurnameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactUsSurnameFieldKeyPressed(evt);
            }
        });

        ContactUsEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsEmailLabel.setText("Email");

        ContactUsEmailField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsEmailField.setToolTipText("Please enter your email into this field, for e.g. 'michael.moore@example.com'");
        ContactUsEmailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactUsEmailFieldKeyPressed(evt);
            }
        });

        SendFeedbackBTN.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        SendFeedbackBTN.setText("Send");
        SendFeedbackBTN.setToolTipText("After you've filled out all of the fields above and want to submit your review, please press this 'send' button.\n");
        SendFeedbackBTN.setMaximumSize(new java.awt.Dimension(72, 22));
        SendFeedbackBTN.setMinimumSize(new java.awt.Dimension(72, 22));
        SendFeedbackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendFeedbackBTNActionPerformed(evt);
            }
        });

        exitBTn5.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn5.setText("EXIT");
        exitBTn5.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn5.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn5.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContactUsPNLLayout = new javax.swing.GroupLayout(ContactUsPNL);
        ContactUsPNL.setLayout(ContactUsPNLLayout);
        ContactUsPNLLayout.setHorizontalGroup(
            ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactUsPNLLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(FeedbackLabel)
                .addGap(18, 18, 18)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addComponent(TermsAndConditionsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(TermsAndConditionsCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContactUsEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContactUsFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContactUsPNLLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContactUsSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ContactUsSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContactUsPNLLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(ReviewDateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ReviewDateFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addComponent(FeedbackTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(ContactUsPNLLayout.createSequentialGroup()
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(ContactUsEmailLabel))
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ContactUsFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(SendFeedbackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(exitBTn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(ContactUsTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContactUsPNLLayout.setVerticalGroup(
            ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactUsPNLLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(ContactUsTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactUsFirstNameLabel)
                    .addComponent(ContactUsFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactUsSurnameLabel)
                    .addComponent(ContactUsSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReviewDateLabel)
                    .addComponent(ReviewDateFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactUsEmailLabel)
                    .addComponent(ContactUsEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FeedbackLabel)
                    .addComponent(FeedbackTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TermsAndConditionsLabel)
                    .addComponent(TermsAndConditionsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendFeedbackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBTn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        Parent.add(ContactUsPNL, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HomePagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContactUsFirstNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactUsFirstNameFieldKeyPressed

    }//GEN-LAST:event_ContactUsFirstNameFieldKeyPressed

    private void FeedbackTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FeedbackTextAreaKeyPressed

    }//GEN-LAST:event_FeedbackTextAreaKeyPressed

    private void ReviewDateFormattedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewDateFormattedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReviewDateFormattedFieldActionPerformed

    private void ReviewDateFormattedFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReviewDateFormattedFieldKeyPressed
     
    }//GEN-LAST:event_ReviewDateFormattedFieldKeyPressed

    private void ContactUsSurnameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactUsSurnameFieldKeyPressed

    }//GEN-LAST:event_ContactUsSurnameFieldKeyPressed

    private void ContactUsEmailFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactUsEmailFieldKeyPressed

    }//GEN-LAST:event_ContactUsEmailFieldKeyPressed

    private void SendFeedbackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendFeedbackBTNActionPerformed

    }//GEN-LAST:event_SendFeedbackBTNActionPerformed

    private void ContactUsFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactUsFirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactUsFirstNameFieldActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void SurnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurnameFieldActionPerformed

    private void ReportGeneratorLogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportGeneratorLogoLabelMouseClicked
        Parent.removeAll();
        Parent.add(ReportGeneratorPNL);
        Parent.repaint();
        Parent.revalidate();

    }//GEN-LAST:event_ReportGeneratorLogoLabelMouseClicked

    private void RecourceHubLogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecourceHubLogoLabelMouseClicked
        Parent.removeAll();
        Parent.add(RecourceHubPNL);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_RecourceHubLogoLabelMouseClicked

    private void ContactUsLogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactUsLogoLabelMouseClicked
        Parent.removeAll();
        Parent.add(ContactUsPNL);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_ContactUsLogoLabelMouseClicked

    private void TutorialLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TutorialLabelMouseClicked
        SecondParent.removeAll();
        SecondParent.add(TutorialsPNL);
        SecondParent.repaint();
        SecondParent.revalidate();
    }//GEN-LAST:event_TutorialLabelMouseClicked

    private void QuizLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuizLabelMouseClicked
        SecondParent.removeAll();
        SecondParent.add(QuizPNL);
        SecondParent.repaint();
        SecondParent.revalidate();
    }//GEN-LAST:event_QuizLabelMouseClicked

    private void ManageRecourceLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageRecourceLabelMouseClicked
        SecondParent.removeAll();
        SecondParent.add(ManageRecourcesPNL);
        SecondParent.repaint();
        SecondParent.revalidate();
    }//GEN-LAST:event_ManageRecourceLabelMouseClicked

    private void RecourseSurnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecourseSurnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecourseSurnameFieldActionPerformed

    private void SaveRecourseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveRecourseBTNActionPerformed
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String FirstName = FirstNameField.getText();//getting the text from the fields listed
        String Surname = SurnameField.getText();
        String Course = RecourseCourseField.getText();
        String Date = RecourseDateField.getText();
        String Type = (String) RecourceTypeComboBox.getSelectedItem();
        String url = RecourseURLField.getText();

        try {//try catch to catch any issues
            outFile = new File("Recources.txt");//txt file called Recources
            fw = new FileWriter(outFile, true);//fw is my filewriter
            bw = new BufferedWriter(fw);//fw is my BufferedWriterS

            bw.write(FirstName + "," + Surname + "," + Course + "," + Date + "," + Type + "," + url);
            bw.newLine();
            bw.close();

            JOptionPane.showMessageDialog(null, "Succesfully added to the file");

        } catch (IOException e) {
            System.out.println("Exception e: " + e.getMessage());
        }
    }//GEN-LAST:event_SaveRecourseBTNActionPerformed

    private void ViewRecourceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRecourceBTNActionPerformed
        File inFile = new File("Recources.txt");

        try (BufferedReader br = new BufferedReader(new FileReader(inFile))) {
            DefaultTableModel tableModel = (DefaultTableModel) RecourseTBL.getModel();
            tableModel.setRowCount(0);

            String ln;
            while ((ln = br.readLine()) != null) {
                String[] row = ln.split(",");

                if (row.length == tableModel.getColumnCount()) {
                    tableModel.addRow(row);
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Unallignment between file rows and table rowa.\nCheck the file format.",
                            "Data Error",
                            JOptionPane.WARNING_MESSAGE);
                    break;
                }
            }
        } catch (IOException ex) {
            // Show an error dialog if there's an issue reading the file
            JOptionPane.showMessageDialog(null,
                    "Error reading file: " + ex.getMessage(),
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ViewRecourceBTNActionPerformed

    private void DateFormattedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateFormattedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFormattedFieldActionPerformed

    private void exitBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTnActionPerformed
        setVisible(false);

        // Open the HomePage
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_exitBTnActionPerformed

    private void exitBTn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTn1ActionPerformed
                setVisible(false);

        // Open the HomePage
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_exitBTn1ActionPerformed

    private void exitBTn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTn2ActionPerformed
         setVisible(false);

        // Open the HomePage
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_exitBTn2ActionPerformed

    private void exitBTn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTn3ActionPerformed
                setVisible(false);

        // Open the HomePage
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_exitBTn3ActionPerformed

    private void exitBTn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTn4ActionPerformed
                setVisible(false);

        // Open the HomePage
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_exitBTn4ActionPerformed

    private void exitBTn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTn5ActionPerformed
                setVisible(false);

        // Open the HomePage
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_exitBTn5ActionPerformed

    private void exitBTn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTn6ActionPerformed
        // TODO add your handling code here:
                setVisible(false);

        // Open the HomePage
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_exitBTn6ActionPerformed

    private void ComputersQuizCheckBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputersQuizCheckBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComputersQuizCheckBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarmEducationalEnviormentGUIGregory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarmEducationalEnviormentGUIGregory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarmEducationalEnviormentGUIGregory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarmEducationalEnviormentGUIGregory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarmEducationalEnviormentGUIGregory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComputerQuizComboBox;
    private javax.swing.JComboBox<String> ComputerQuizComboBox2;
    private javax.swing.JComboBox<String> ComputerQuizComboBox3;
    private javax.swing.JComboBox<String> ComputerQuizComboBox4;
    private javax.swing.JComboBox<String> ComputerQuizComboBox5;
    private javax.swing.JButton ComputersClearBTN;
    private javax.swing.JLabel ComputersQuestionLabel1;
    private javax.swing.JLabel ComputersQuestionLabel2;
    private javax.swing.JLabel ComputersQuestionLabel3;
    private javax.swing.JLabel ComputersQuestionLabel4;
    private javax.swing.JLabel ComputersQuestionLabel5;
    private javax.swing.JButton ComputersQuizCheckBTN;
    private javax.swing.JPanel ComputersQuizPNL;
    public static javax.swing.JTextField ContactUsEmailField;
    private javax.swing.JLabel ContactUsEmailLabel;
    public static javax.swing.JTextField ContactUsFirstNameField;
    private javax.swing.JLabel ContactUsFirstNameLabel;
    private javax.swing.JLabel ContactUsLabel;
    private javax.swing.JLabel ContactUsLogoLabel;
    private javax.swing.JPanel ContactUsPNL;
    public static javax.swing.JTextField ContactUsSurnameField;
    private javax.swing.JLabel ContactUsSurnameLabel;
    private javax.swing.JLabel ContactUsTitleLabel;
    private javax.swing.JLabel ContentLabel;
    private javax.swing.JTextArea ContentTextArea;
    private javax.swing.JLabel CourseLabel;
    private javax.swing.JFormattedTextField DateFormattedField;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel FeedbackLabel;
    public static javax.swing.JTextArea FeedbackTextArea;
    private javax.swing.JScrollPane FeedbackTextAreaScrollPane;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JButton GeographyClearBTN1;
    private javax.swing.JLabel GeographyQuestionLabel1;
    private javax.swing.JLabel GeographyQuestionLabel2;
    private javax.swing.JLabel GeographyQuestionLabel3;
    private javax.swing.JLabel GeographyQuestionLabel4;
    private javax.swing.JLabel GeographyQuestionLabel5;
    private javax.swing.JButton GeographyQuizCheckBTN;
    private javax.swing.JComboBox<String> GeographyQuizComboBox;
    private javax.swing.JComboBox<String> GeographyQuizComboBox2;
    private javax.swing.JComboBox<String> GeographyQuizComboBox3;
    private javax.swing.JComboBox<String> GeographyQuizComboBox4;
    private javax.swing.JComboBox<String> GeographyQuizComboBox5;
    private javax.swing.JPanel GeographyQuizPNL;
    private javax.swing.JPanel HomePagePanel;
    private javax.swing.JLabel ManageRecourceLabel;
    private javax.swing.JPanel ManageRecourcesPNL;
    private javax.swing.JPanel Parent;
    private javax.swing.JButton ProgrammingClearBTN;
    private javax.swing.JComboBox<String> ProgrammingComboBox;
    private javax.swing.JComboBox<String> ProgrammingComboBox2;
    private javax.swing.JComboBox<String> ProgrammingComboBox3;
    private javax.swing.JComboBox<String> ProgrammingComboBox4;
    private javax.swing.JComboBox<String> ProgrammingComboBox5;
    private javax.swing.JLabel ProgrammingQuestionLabel1;
    private javax.swing.JLabel ProgrammingQuestionLabel2;
    private javax.swing.JLabel ProgrammingQuestionLabel3;
    private javax.swing.JLabel ProgrammingQuestionLabel4;
    private javax.swing.JLabel ProgrammingQuestionLabel5;
    private javax.swing.JButton ProgrammingQuizCheckBTN;
    private javax.swing.JPanel ProgrammingQuizPNL;
    private javax.swing.JLabel QuizLabel;
    private javax.swing.JPanel QuizPNL;
    private javax.swing.JLabel RecourceFirstNameLabel;
    private javax.swing.JLabel RecourceHubLabel;
    private javax.swing.JLabel RecourceHubLogoLabel;
    private javax.swing.JPanel RecourceHubNavPNL;
    private javax.swing.JPanel RecourceHubPNL;
    private javax.swing.JComboBox<String> RecourceTypeComboBox;
    private javax.swing.JLabel RecourcesSurnameLabel;
    private javax.swing.JTextField RecourseCourseField;
    private javax.swing.JTextField RecourseDateField;
    private javax.swing.JLabel RecourseDateLabel;
    private javax.swing.JTextField RecourseFirstNameField;
    private javax.swing.JTextField RecourseSurnameField;
    private javax.swing.JTable RecourseTBL;
    private javax.swing.JLabel RecourseTypeLabel;
    private javax.swing.JTextField RecourseURLField;
    private javax.swing.JLabel ReportGeneratorLabel;
    private javax.swing.JLabel ReportGeneratorLabel1;
    private javax.swing.JLabel ReportGeneratorLabel2;
    private javax.swing.JLabel ReportGeneratorLabel3;
    private javax.swing.JLabel ReportGeneratorLogoLabel;
    private javax.swing.JPanel ReportGeneratorPNL;
    private javax.swing.JLabel ReportGeneratorTitleLabel;
    private javax.swing.JFormattedTextField ReviewDateFormattedField;
    private javax.swing.JLabel ReviewDateLabel;
    private javax.swing.JButton SaveBTN;
    private javax.swing.JButton SaveRecourseBTN;
    private javax.swing.JPanel SecondParent;
    public static javax.swing.JButton SendFeedbackBTN;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel SurnameLabel;
    private javax.swing.JCheckBox TermsAndConditionsCheckBox;
    private javax.swing.JLabel TermsAndConditionsLabel;
    private javax.swing.JLabel Tutorial1Label;
    private javax.swing.JLabel TutorialLabel;
    private javax.swing.JLabel TutorialLabel2;
    private javax.swing.JLabel TutorialLabel3;
    private javax.swing.JLabel TutorialLabel4;
    private javax.swing.JLabel TutorialLabel5;
    private javax.swing.JLabel TutorialNameLabel;
    private javax.swing.JLabel TutorialNameLabel2;
    private javax.swing.JLabel TutorialNameLabel3;
    private javax.swing.JLabel TutorialNameLabel4;
    private javax.swing.JLabel TutorialNameLabel5;
    private javax.swing.JPanel TutorialsPNL;
    private javax.swing.JLabel URLLabel;
    private javax.swing.JButton ViewBTN;
    private javax.swing.JButton ViewRecourceBTN;
    private javax.swing.JButton exitBTn;
    private javax.swing.JButton exitBTn1;
    private javax.swing.JButton exitBTn2;
    private javax.swing.JButton exitBTn3;
    private javax.swing.JButton exitBTn4;
    private javax.swing.JButton exitBTn5;
    private javax.swing.JButton exitBTn6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
